// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for android - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for iOS - '
              'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }


  static const FirebaseOptions web = FirebaseOptions(
    apiKey: "AIzaSyB7N32X4q2EeB7Wyg-MhJwPX3drtPD4BLg",
    appId: "1:1064974951310:web:0ffeef6b8bbb502a1cbadf",
    messagingSenderId: "1064974951310",
    projectId: "crm-ondo-db",
    authDomain: "crm-ondo-db.firebaseapp.com",
    storageBucket: "crm-ondo-db.appspot.com",
    measurementId: "G-DLELVWPBZR",
  );

  // static const FirebaseOptions android = FirebaseOptions(
  //   apiKey: 'AIzaSyBgSqBo035ZvCtMx7evPVpiNqpNKAbs57U',
  //   appId: '1:240358778486:android:05c9d2a1f9c3c307dfa157',
  //   messagingSenderId: '240358778486',
  //   projectId: 'unixp-7077e',
  //   storageBucket: 'unixp-7077e.appspot.com',
  // );
  //
  // static const FirebaseOptions ios = FirebaseOptions(
  //   apiKey: 'AIzaSyBqLbF1IWuXkTp2GYcl-gXXXMaeYVLMYcA',
  //   appId: '1:240358778486:ios:721a80b6f52140e9dfa157',
  //   messagingSenderId: '240358778486',
  //   projectId: 'unixp-7077e',
  //   storageBucket: 'unixp-7077e.appspot.com',
  //   iosClientId: '240358778486-gf9pha6guojqf9aq2k4o1o3diodhtl5t.apps.googleusercontent.com',
  //   iosBundleId: 'com.example.onboardingScreens',
  // );
}
